'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),vm=require('vm'),crypto=require('crypto');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');new vm.Script(html.match(/<script\b[^>]*>([\s\S]*?)<\/script>/i)[1]);
for(const old of ['avatarSVG1478','spriteStyle152','renderPortraitCreator1479','renderPortraitCreator150','renderPortraitCreator151','npc_portraits_sheet','player_portraits_30','player_preset_sheet','async function composeAppearance','bodyURL(a)','detail(k,i)'])assert(!html.includes(old),old+' removed');
const pw=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,b)=>{res.writeHead(err?404:200,{'Content-Type':file.endsWith('.html')?'text/html':file.endsWith('.webp')?'image/webp':'application/json'});res.end(err?'missing':b);});});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(8765,'127.0.0.1',r));browser=await pw.chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],missing=[],layerRequests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('/assets/portraits/')&&r.status()>=400)missing.push(r.url());});page.on('request',r=>{if(/\/portraits\/(layers|bodies|thumbs|player-v2)\//.test(r.url()))layerRequests.push(r.url());});
 await page.goto('http://127.0.0.1:8765/');const data=await page.evaluate(()=>PortraitResolver.data);assert.equal(data.npc.length,27);assert.equal(data.player.length,30);const hashes=new Set();for(const p of [...data.npc,...data.player]){assert(fs.existsSync(path.join(root,p.portrait)));hashes.add(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p.portrait))).digest('hex'));}assert.equal(hashes.size,57);
 assert.equal(data.npc.find(n=>n.name==='肖恩').gender,'male');assert.equal(data.npc.find(n=>n.name==='杨杨').gender,'female');assert.equal(data.npc.find(n=>n.id==='kzong').age,'30–35');await page.evaluate(()=>buildCast());assert(!/[0-9]+[–-][0-9]+岁|三十多岁|微胖|强壮体型/.test(await page.locator('#cast-wrap').textContent()));
 await page.evaluate(()=>Promise.all(PortraitResolver.data.npc.map(p=>new Promise((r,j)=>{const im=new Image();im.onload=r;im.onerror=j;im.src=p.portrait;}))));await page.evaluate(()=>openCreatorScreen());assert.equal(await page.locator('.cc-preview-photo').count(),0);
 await page.locator('[data-gender="female"]').click();await page.locator('[data-age="g3"]').click();await page.locator('[data-step="2"]').click();assert.equal(await page.locator('[data-preset]').count(),3);assert.equal(await page.locator('[data-group]').count(),0);
 for(const g of ['female','male'])for(const a of ['g1','g2','g3','g4','g5']){
  await page.evaluate(([g,a])=>{CharacterCreatorV2.identity('gender',g);CharacterCreatorV2.identity('age',a);},[g,a]);assert.equal(await page.locator('.cc-preview-photo').count(),0);const pool=await page.evaluate(()=>CharacterCreatorV2.pool());assert.equal(pool.length,3);
  for(const p of pool){await page.locator('[data-preset="'+p.id+'"]').click();await page.evaluate(()=>CharacterCreatorV2.pending);assert.equal(await page.evaluate(()=>CharacterCreatorV2.error),'');assert.equal(await page.locator('.cc-preview-photo').getAttribute('src'),p.portrait);assert.equal(await page.locator('[data-preset="'+p.id+'"] img').getAttribute('src'),p.portrait);assert(await page.locator('.cc-preview-photo').evaluate(im=>im.complete&&im.naturalWidth>0&&Math.abs(im.naturalWidth/im.naturalHeight-.75)<.01));}
 }
 await page.evaluate(async()=>{CharacterCreatorV2.identity('gender','female');CharacterCreatorV2.identity('age','g3');CharacterCreatorV2.select('f_g3_a');CharacterCreatorV2.identity('gender','male');await CharacterCreatorV2.pending;});assert.equal(await page.evaluate(()=>CharacterCreatorV2.busy),false);assert.equal(await page.locator('.cc-preview-photo').count(),0);
 await page.evaluate(async()=>{CharacterCreatorV2.identity('age','g5');CharacterCreatorV2.select('m_g5_c');await CharacterCreatorV2.pending;await CharacterCreatorV2.confirm();});assert(await page.evaluate(()=>!!CharacterCreatorV2.confirmed));
 for(const n of [3,4,5,3,5]){await page.evaluate(n=>CharacterCreatorV2.go(n),n);if(n===3)assert.equal(await page.locator('#cc-ng-slot #ng-panel').count(),1);if(n===5)assert.equal(await page.locator('#cc-difficulty-slot .difficulty-wrap').count(),1);}
 await page.locator('#creator-v2-root button[onclick="startGame()"]').click();assert.equal(await page.evaluate(()=>S.player.gender),'male');assert.equal(await page.evaluate(()=>S.player.age),'g5');assert.equal(await page.locator('.pm-player-photo').getAttribute('src'),data.player.find(p=>p.id==='m_g5_c').portrait);
 assert(await page.evaluate(()=>saveGameV2()));const saved=await page.evaluate(()=>JSON.stringify(S));await page.reload();assert(await page.evaluate(()=>loadGameV2()));assert.equal(await page.evaluate(()=>JSON.stringify(S)),saved);
 const migrated=await page.evaluate(async()=>{const raw=localStorage.getItem('dragon_save_v2'),save=JSON.parse(raw),before=JSON.stringify(save.state.player.skills);save.state.player.appearance={...save.state.player.appearance,version:2,portraitRenderer:2,portraitURL:'data:image/webp;base64,oldMisalignedAccessories',accessory:9,makeup:9,pose:5};delete save.state.campaign;save.chapterIdx=2;save.chapterIds[2]='v12_3_overload';localStorage.setItem('dragon_save_v2',JSON.stringify(save));const ok=await loadGameV2(),result={ok,id:runChapters[2].id,appearance:S.player.appearance,skills:JSON.stringify(S.player.skills)===before,migrated:S.campaign.migrated};localStorage.setItem('dragon_save_v2',raw);await loadGameV2();return result;});assert(migrated.ok&&migrated.skills&&migrated.migrated);assert.equal(migrated.id,'v11_3');assert.equal(migrated.appearance.portraitRenderer,3);assert.equal(migrated.appearance.basePreset,'m_g5_c');assert(!('accessory' in migrated.appearance));assert(!('makeup' in migrated.appearance));assert.equal(migrated.appearance.portraitURL,data.player.find(p=>p.id==='m_g5_c').portrait);
 await page.evaluate(()=>renderVP());assert.equal(await page.locator('#vp-card .vp-portrait-final').getAttribute('src'),data.npc.find(n=>n.name==='钟时').portrait);await page.evaluate(()=>{document.getElementById('scene-area').innerHTML=dialogueHTML('肖恩：「先看记录。」\n\n杨杨：「明天完成。」','肖恩');});assert.equal(await page.locator('.dialogue-portrait-img').count(),2);
 await page.evaluate(()=>{openCreatorScreen();CharacterCreatorV2.go(2);});await page.screenshot({path:path.join(__dirname,'creator-simple-desktop.png'),fullPage:true});for(const width of [390,768]){await page.setViewportSize({width,height:844});await page.evaluate(()=>CharacterCreatorV2.go(2));await page.screenshot({path:path.join(__dirname,'creator-simple-'+width+'.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await page.locator('[data-preset]').count(),3);assert.equal(await page.locator('[data-group]').count(),0);}
 assert.deepEqual(layerRequests,[]);assert.deepEqual(missing,[]);assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',fullTemplates:30,npc:27,partsCustomization:0,layerRequests:0,legacyPortraitMigration:true,legacyChapterMigration:true,saveLoad:true,mobile:[390,768],errors},null,2));
 }finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
