'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const pw=require(process.env.PLAYWRIGHT_MODULE||'playwright'),root=path.join(__dirname,'..'),out=process.env.UI_OUTPUT||__dirname;
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,b)=>{res.writeHead(err?404:200,{'Content-Type':file.endsWith('.html')?'text/html':file.endsWith('.webp')?'image/webp':'application/octet-stream'});res.end(err?'missing':b);});});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(8767,'127.0.0.1',r));browser=await pw.chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8767/');await page.screenshot({path:path.join(out,'office-title.png'),fullPage:true});
 assert.match(await page.locator('#title-screen .subtitle').innerText(),/v18\.2\.0/);assert(await page.locator('#ow-dock').isHidden());await page.locator('.ow-title-banner button').first().click();await page.locator('[data-gender="female"]').click();await page.locator('[data-age="g3"]').click();await page.locator('[data-step="2"]').click();await page.locator('[data-preset="f_g3_b"]').click();await page.evaluate(()=>CharacterCreatorV2.pending);assert.match(await page.locator('.ow-id-badge').innerText(),/PENDING|F_G3_B/);await page.screenshot({path:path.join(out,'office-onboarding.png'),fullPage:true});await page.locator('#cc-confirm-look').click();await page.evaluate(()=>{selectedDifficulty='story';startGame();});await page.waitForTimeout(100);
 assert(await page.locator('#ow-dock').isVisible());assert(await page.locator('.ow-stage').isVisible());assert.equal(await page.locator('#npcs .npc-chip').count(),0);assert((await page.locator('#npcs .ow-tag').count())<=5);assert.equal(await page.locator('.ow-scene-portrait').getAttribute('src'),await page.evaluate(()=>PortraitResolver.url(ProjectCampaignV2.data.chapters[0].from)));
 const layout=await page.evaluate(()=>Object.fromEntries(['hud','pm-left-panel','scene-area','pm-right-panel'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return[id,{x:r.x,y:r.y,width:r.width}];})));assert(layout['scene-area'].width>550,'central narrative receives the largest column');assert(layout.hud.width>1300,'HUD spans entire workspace');assert(layout['pm-left-panel'].x<layout['scene-area'].x&&layout['scene-area'].x<layout['pm-right-panel'].x,'employee / narrative / dashboard order');
 const before=await page.evaluate(()=>JSON.stringify(S));await page.locator('#ow-dock button').filter({hasText:'联系'}).click();assert(await page.locator('#ow-dialog').isVisible());assert((await page.locator('.ow-person').count())<27);await page.keyboard.press('Escape');assert(await page.locator('#ow-dialog').isHidden());
 assert.deepEqual(await page.evaluate(()=>Object.values(OfficeWorkspace.folders).flatMap(x=>x.items).filter(x=>typeof window[x[0]]!=='function').map(x=>x[0])),[],'all categorized entries retain real actions');
 await page.locator('#ow-dock button').filter({hasText:'日程'}).click();assert.equal(await page.locator('.ow-calendar').count(),5);await page.keyboard.press('Escape');await page.locator('#ow-dock button').filter({hasText:'纪要'}).click();assert.equal(await page.locator('.ow-record').count(),await page.evaluate(()=>S.log.length));await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>JSON.stringify(S)),before,'read-only tools do not alter gameplay');
 await page.locator('button[onclick="pickChapter(0)"]').hover();assert.match(await page.locator('#ow-estimate').innerText(),/预计/);assert(await page.locator('[data-resource="stamina"] .ow-ghost').isVisible());await page.mouse.move(0,0);assert(await page.locator('[data-resource="stamina"] .ow-ghost').isHidden());
 await page.evaluate(()=>OfficeWorkspace.open('work'));await page.locator('#ow-dialog button').filter({hasText:'收件箱与留痕'}).click();assert.match(await page.locator('#scene-area').innerText(),/收件箱/);await page.locator('#ow-dock .ow-play').click();assert(await page.locator('button[onclick="pickChapter(0)"]').isVisible());
 await page.locator('button[onclick="pickChapter(0)"]').hover();assert.match(await page.locator('#ow-estimate').innerText(),/预计/);await page.mouse.move(0,0);
 await page.evaluate(()=>{OfficeWorkspace.launch('showGrowthShop');OfficeWorkspace.resume();});assert(await page.locator('button[onclick="pickChapter(0)"]').isVisible());
 assert(await page.locator('#ow-save-work').isVisible());await page.locator('#ow-save-work').click();assert.match(await page.locator('#ow-save-status').innerText(),/上次保存：第1章/);assert(!/有未保存/.test(await page.locator('#ow-save-status').innerText()));const saved=await page.evaluate(()=>JSON.stringify(S));await page.reload();await page.evaluate(()=>loadGameV2());assert.equal(await page.evaluate(()=>JSON.stringify(S)),saved);await page.waitForTimeout(100);
 await page.screenshot({path:path.join(out,'office-game-desktop.png'),fullPage:true});
 for(const width of [768,390]){await page.setViewportSize({width,height:844});await page.waitForTimeout(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal overflow '+width);await page.screenshot({path:path.join(out,'office-game-'+width+'.png'),fullPage:true});await page.evaluate(()=>OfficeWorkspace.open('system'));assert(await page.locator('#ow-dialog').isVisible());assert(await page.locator('#ow-dialog').evaluate(n=>n.getBoundingClientRect().right<=innerWidth));await page.keyboard.press('Escape');}
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{S.heart=25;S.stamina=20;renderHUD();});assert(await page.locator('body.ow-strained').count());assert.equal(await page.locator('.ow-gauge.danger').count(),2);
 await page.evaluate(()=>{OfficeWorkspace.archive();});assert.match(await page.locator('#ow-dialog').innerText(),/权限不足/);assert.match(await page.locator('#ow-dialog').innerText(),/年度绩效/);await page.keyboard.press('Escape');
 await page.evaluate(()=>{window._evObj={ev:{title:'夜间来电',from:'杨杨',phone:true,text:'杨杨：「明天核对这份材料。」',choices:[{t:'先留下核对记录。',e:{},r:'收到。'}]},next:()=>{},cro:false};renderEventFromObj();});await page.waitForTimeout(100);assert(await page.locator('.scene.ow-online').count());assert.equal(await page.locator('.ow-scene-portrait').getAttribute('src'),await page.evaluate(()=>PortraitResolver.url('杨杨')));await page.screenshot({path:path.join(out,'office-messenger.png'),fullPage:true});
 await page.evaluate(()=>{window._evObj.ev.from='家里';renderEventFromObj();});await page.waitForTimeout(100);assert.equal(await page.locator('.ow-scene-portrait').count(),0,'private caller never borrows an NPC face');assert(await page.locator('.ow-anonymous').isVisible());
 await page.evaluate(()=>showResult('这是尚未确认的结算。',[],()=>{}));await page.evaluate(()=>{OfficeWorkspace.resume();OfficeWorkspace.launch('showRest');});assert(await page.locator('button[onclick="continueResult()"]').isVisible(),'dock cannot skip pending result');
 const safeSave=await page.evaluate(()=>localStorage.getItem('dragon_save_v2'));await page.evaluate(()=>OfficeWorkspace.launch('saveGameV2'));assert.equal(await page.evaluate(()=>localStorage.getItem('dragon_save_v2')),safeSave,'pending result cannot overwrite safe save');
 // UI-only boundary fixture: verify irreversible confirmation without claiming reachability.
 await page.evaluate(()=>{window._evObj=null;window._next=null;S.stamina=80;S.heart=80;chapterIdx=13;renderChapter();});await page.waitForTimeout(100);assert(await page.locator('.ow-query-head').isVisible());const fraud=await page.evaluate(()=>runChapters[13].choices.findIndex(c=>c.campaignChoice.kind==='fraud')),beforeSignature=await page.evaluate(()=>JSON.stringify(S));await page.locator('button[onclick="pickChapter('+fraud+')"]').click();assert.match(await page.locator('#ow-dialog').innerText(),/Audit Trail/);assert.equal(await page.evaluate(()=>JSON.stringify(S)),beforeSignature,'opening confirmation does not apply choice');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>JSON.stringify(S)),beforeSignature);await page.locator('button[onclick="pickChapter('+fraud+')"]').click();await page.locator('button[onclick="OfficeWorkspace.confirmChoice()"]').click();assert(await page.evaluate(()=>S.campaign.flags.fraud),'confirmed choice uses original campaign action');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',layout:[1440,768,390],contextualContacts:true,readOnlyNavigation:true,hoverPreview:true,onboardingBadge:true,saveLoad:true,onlineEvent:true,errors},null,2));
 }finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
