'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),pw=require(process.env.PLAYWRIGHT_MODULE||'playwright'),root=path.join(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':file.endsWith('.html')?'text/html':file.endsWith('.webp')?'image/webp':'application/octet-stream'});res.end(e?'missing':b);});});
(async()=>{let browser;try{
 await new Promise(r=>server.listen(8773,'127.0.0.1',r));browser=await pw.chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8773');
 await page.evaluate(async()=>{openCreatorScreen();CharacterCreatorV2.identity('gender','female');CharacterCreatorV2.identity('age','g4');CharacterCreatorV2.select('f_g4_b');await CharacterCreatorV2.pending;await CharacterCreatorV2.confirm();selectedDifficulty='story';startGame();S.player.traits=Object.keys(StoryTraitOptions.rules);S.campaign.cash=100000;maybeEvent=(id,next)=>next();maybePhoneEvent=next=>next();maybeProjectBattle=(id,next)=>next();maybeRomanceEncounter=next=>next();maybeLove=next=>next();maybeResourceConflict=next=>next();maybePrivateChat=next=>next();});
 for(const id of await page.evaluate(()=>Object.keys(StoryTraitOptions.rules))){await page.evaluate(id=>{chapterIdx=StoryTraitOptions.rules[id].chapters[0];renderChapter();},id);assert(await page.locator('button[data-trait="'+id+'"]').isVisible(),id);}
 await page.evaluate(()=>{chapterIdx=12;renderChapter();});for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('button[data-trait="relationshipwise"]').isVisible());}
 await page.evaluate(()=>{chapterIdx=15;renderChapter();});assert.match(await page.locator('button[data-trait="nda"]').innerText(),/金色传说/);const preview=await page.evaluate(()=>{const c=runChapters[15].choices.find(c=>c.campaignChoice.trait==='nda');return {cost:costStamina(c),before:S.stamina};});await page.locator('button[data-trait="nda"]').click();assert(await page.evaluate(()=>!!S.campaign.traitUses.nda));assert.equal(await page.evaluate(()=>S.stamina),preview.before-preview.cost);const saved=await page.evaluate(()=>JSON.stringify(S.campaign.traitUses));await page.evaluate(()=>continueResult());assert(await page.evaluate(()=>saveGameV2()));await page.reload();await page.evaluate(()=>loadGameV2());assert.equal(await page.evaluate(()=>JSON.stringify(S.campaign.traitUses)),saved);await page.evaluate(()=>{chapterIdx=15;renderChapter();});assert.equal(await page.locator('button[data-trait="nda"]').count(),0);assert.deepEqual(errors,[]);console.log('PASS trait browser:27 visible responses, golden styling,1440/768/390, real click/cost, save/reload and one-use persistence.');
 }finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
